### ISSUE TITLE
Add better tooling/examples for storing, retrieving, and handling metrics in pin metadata

### ISSUE THREAD

**Issue by tyluRp** [rstudio/vetiver-r#109]
I want to monitor how my model has performed throughout development, e.g. v1, v2, v3, etc. I would have something like this for each version:

|.metric              |.estimator | .estimate|
|:--------------------|:----------|---------:|
|accuracy             |binary     | 0.8012232|
|kap                  |binary     | 0.5047648|
|sens                 |binary     | 0.8908297|
|spec                 |binary     | 0.5918367|
|ppv                  |binary     | 0.8360656|
|npv                  |binary     | 0.6987952|
|mcc                  |binary     | 0.5080938|
|j_index              |binary     | 0.4826664|
|bal_accuracy         |binary     | 0.7413332|
|detection_prevalence |binary     | 0.7461774|
|precision            |binary     | 0.8360656|
|recall               |binary     | 0.8908297|
|f_meas               |binary     | 0.8625793|

I would then have data I can use to see how the model has performed over time. I do not have a date column in my data however and so I have a feeling that I am misinterpreting the intended use of vetiver's monitoring system. Is vetiver's intention to compare the performance of various iterations of a model?

**Comment by juliasilge** [comment]
This is an interesting question that in some ways we are still figuring out. However, I do think the scope of vetiver starts _after_ model development when you have chosen a model to deploy; it's not meant for experiment tracking, for example.

If you are a tidymodels user, you may be interested in workflowsets, which has infrastructure, methods, plotting, etc for comparing different model workflows (combinations of feature engineering + model):
https://workflowsets.tidymodels.org/
You don't necessarily have to start with a workflow set; you can [create one from](https://workflowsets.tidymodels.org/reference/as_workflow_set.html) existing resampling results.


Here are two sections of our book to learn more about multiple workflows at once:
- https://www.tmwr.org/workflows.html#workflow-sets-intro
- https://www.tmwr.org/workflow-sets.html

**Comment by juliasilge** [comment]
Yes, absolutely! I have some TODOs around about showing this, but the basic idea is like this:

``` r
library(tidymodels)
data(bivariate)

biv_rec <-
    recipe(Class ~ ., data = bivariate_train) %>%
    step_BoxCox(all_predictors())%>%
    step_normalize(all_predictors())

svm_spec <-
    svm_linear(mode = "classification") %>%
    set_engine("LiblineaR")

svm_fit <- workflow() %>%
    add_recipe(biv_rec) %>%
    add_model(svm_spec) %>%
    fit(bivariate_train)

vetiver_metrics <-
    augment(svm_fit, bivariate_test) %>%
    metrics(Class, .pred_class)

library(vetiver)
#> 
#> Attaching package: 'vetiver'
#> The following object is masked from 'package:tune':
#> 
#>     load_pkgs
v <- vetiver_model(svm_fit, "biv_svm", metadata = list(metrics = vetiver_metrics))
v
#> 
#> ── biv_svm ─ <butchered_workflow> model for deployment 
#> A LiblineaR classification modeling workflow using 2 features
```

<sup>Created on 2022-06-29 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

**Comment by juliasilge** [comment]
We set up a new article that demonstrates how to store, retrieve, and handle model metrics:
https://vetiver.rstudio.com/learn-more/metrics-metadata.html

Let us know if you have further questions on how to approach this!
