### ISSUE TITLE
Specify pin type in vetiver_pin_metrics?

### ISSUE THREAD

**Issue by machow** [rstudio/vetiver-r#118]
Currently vetiver_pin_model does not have an options to specify pin type. I think this means that pins will be stored as Rds files. However, in pins-python the type argument is required. Should we add a type argument to vetiver_pin_model? Alternatively, it could re-use the type of the pin it is writing a new version to.

`pin_write` can also take other arguments. For example, with the rstudio board a person might do `pin_write(..., access_type="all")`. I wonder if we should pass `...` args in to `pin_write`?

(I think a similar situation arises with not being able to pass  args like access_type occurs with `vetiver_pin_write`)

See https://pins.rstudio.com/reference/board_rsconnect.html#public-pins

**Comment by juliasilge** [comment]
I'm guessing you mean `vetiver_pin_metrics()`? Passing in the pin type and using a non-rds default sounds like a good plan. I would guess that CSV would be a decent default type for these small-ish, rectangular datasets of aggregated metrics.

I should add the dots to `vetiver_pin_write` to pass through to pins.

**Comment by machow** [comment]
I added a `pin_type=None` argument to this vetiver-python PR just to get tests passing for now. It defaults to using the same type as the pin being written to (e.g. if the original metrics were saved as arrow, will use arrow). WDYT of that approach? 

In any event, happy to change it to hard-code a type, etc..!

https://github.com/rstudio/vetiver-python/pull/82

**Comment by juliasilge** [comment]
For `vetiver_pin_metrics()`, I am changing this to read the pin type and pin back in the same way. It turns out that `type = "csv"` is a pretty big problem, though, because it uses the default/native R `read.csv()` and that mangles dates (they come in as a FACTOR) and the metrics column, etc. I'm going to check that the original pin was written as RDS or arrow and require that.
