### ISSUE TITLE
Ease developpper addition of new models through `new_model_vetiver(model_class = "your_object", package_name = "your_package")`

### ISSUE THREAD

**Issue by cregouby** [rstudio/vetiver-r#125]
... exactly as {butcher} propose a `new_model_butcher(model_class = "your_object", package_name = "your_package")`.
This would ensure homogeneous code base and tests templates

**Comment by juliasilge** [comment]
We could definitely do this, probably using [cli's support](https://cli.r-lib.org/articles/usethis-ui.html) for this kind of code generation.

I do wonder how many more kinds of models we may end supporting, and if this developer-facing tooling would be a good investment. What kind of model are you interested in having vetiver support?

**Comment by cregouby** [comment]
The kind of model I'm thinking of is tabnet: https://github.com/rstudio/vetiver-r/pull/124, and maybe, later on, other models from packages in [mlverse ecosystem](https://torch.mlverse.org/packages/)...

**Comment by juliasilge** [comment]
I don't expect that we'll have such a large pool of models being added to vetiver (especially since we already support tidymodels, caret, mlr3, etc) that this will be a high need moving forward. Thank you for your input! 🙌
