### ISSUE TITLE
keep $model content when writing to data.txt

### ISSUE THREAD

**Issue by arronlacey** [rstudio/vetiver-r#129]
The output of $model for a vetiver model seems useful to keep when using vetiver_pin_write(board) i.e.
```r
car_mod <-
  workflow(mpg ~ ., linear_reg()) %>%
  fit(mtcars)


v <- vetiver_model(car_mod, "cars_lr")
v$model
```

gives:

```r
══ Workflow [trained] ════════════════════════════════════════════════════════════════════════════════════════
Preprocessor: Formula
Model: linear_reg()

── Preprocessor ──────────────────────────────────────────────────────────────────────────────────────────────
mpg ~ .

── Model ─────────────────────────────────────────────────────────────────────────────────────────────────────

Call:
dummy_call()

Coefficients:
(Intercept)          cyl         disp           hp         drat           wt         qsec           vs  
   12.30337     -0.11144      0.01334     -0.02148      0.78711     -3.71530      0.82104      0.31776  
         am         gear         carb  
    2.52023      0.65541     -0.19942
```

  
Proposal: include the contents of $model when writing to the data.txt file

**Comment by juliasilge** [comment]
Can you explain a little more about what you mean here? The `v$model` object is the whole binary model that we use for prediction; it is what is serialized and then written as a pin to the board. The `data.txt` file isn't where the model object is kept.

**Comment by juliasilge** [comment]
Let me know if you have further questions! 🙌

**Comment by arronlacey** [comment]
sorry @juliasilge totally missed getting round to this. I think I may be leaning too much into model tracking, rather than deployment by wanting to automatically store the metrics from a fitted model *somwhere* other than calling the `v$model` ourselves. I guess maybe I had a `modelsummary.txt` being created along with `data.txt` in mind when I submitted this issue. Does that make sense?

**Comment by juliasilge** [comment]
Ah, if you want to store model metrics when you version I recommend looking into [using the _metadata_ argument](https://rstudio.github.io/vetiver-r/reference/vetiver_model.html) as outlined in #109
