### ISSUE TITLE
error in executing 'vignettes/model-card.Rmd'

### ISSUE THREAD

**Issue by aropele** [rstudio/vetiver-r#130]
Thank you for your work on this project, hello!
I keep getting this error when I try to run the vignette.
The following command was used to create the .Rmd code:

``` r
rmarkdown::draft(
    "my_model_card.Rmd", 
    template = "vetiver_model_card", 
    package = "vetiver"
)
```

Here is the **reprex**:

``` r
library(tidyverse)
library(vetiver)
library(pins)
library(yardstick)
#> For binary classification, the first factor level is assumed to be the event.
#> Use the argument `event_level = "second"` to alter this as needed.
#> 
#> Attaching package: 'yardstick'
#> The following object is masked from 'package:readr':
#> 
#>     spec
knitr::opts_chunk$set(echo = FALSE)
v <- vetiver_pin_read(params$board, params$name, version = params$version)
#> Error in check_board(board, "pin_read()", "pin_get()"): object 'params' not found
v_meta <- pin_meta(params$board, params$name)
#> Error in check_board(board, "pin_meta()", "pin_info()"): object 'params' not found
theme_set(theme_light())
```

<sup>Created on 2022-08-04 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

<details style="margin-bottom:10px;">
<summary>
Session info
</summary>

    #> R version 4.2.1 (2022-06-23 ucrt)
    #> Running under: Windows 10 x64
    #> 
    #> Matrix products: default
    #> 
    #> attached base packages:
    #> [1] stats     graphics  grDevices utils     datasets  methods   base     
    #> 
    #> other attached packages:
    #>  [1] yardstick_1.0.0 pins_1.0.1      vetiver_0.1.6   forcats_0.5.1  
    #>  [5] stringr_1.4.0   dplyr_1.0.9     purrr_0.3.4     readr_2.1.2    
    #>  [9] tidyr_1.2.0     tibble_3.1.8    ggplot2_3.3.6   tidyverse_1.3.2
    #> 
    #> loaded via a namespace (and not attached):
    #>  [1] tidyselect_1.1.2    xfun_0.31           haven_2.5.0        
    #>  [4] gargle_1.2.0        colorspace_2.0-3    vctrs_0.4.1        
    #>  [7] generics_0.1.3      htmltools_0.5.3     yaml_2.3.5         
    #> [10] utf8_1.2.2          rlang_1.0.4         pillar_1.8.0       
    #> [13] glue_1.6.2          withr_2.5.0         DBI_1.1.3          
    #> [16] rappdirs_0.3.3      dbplyr_2.2.1        readxl_1.4.0       
    #> [19] modelr_0.1.8        lifecycle_1.0.1     munsell_0.5.0      
    #> [22] gtable_0.3.0        cellranger_1.1.0    rvest_1.0.2        
    #> [25] evaluate_0.15       knitr_1.39          tzdb_0.3.0         
    #> [28] fastmap_1.1.0       fansi_1.0.3         highr_0.9          
    #> [31] broom_1.0.0         backports_1.4.1     scales_1.2.0       
    #> [34] googlesheets4_1.0.0 jsonlite_1.8.0      fs_1.5.2           
    #> [37] hms_1.1.1           digest_0.6.29       stringi_1.7.8      
    #> [40] grid_4.2.1          cli_3.3.0           tools_4.2.1        
    #> [43] magrittr_2.0.3      crayon_1.5.1        pkgconfig_2.0.3    
    #> [46] ellipsis_0.3.2      xml2_1.3.3          reprex_2.0.1       
    #> [49] googledrive_2.0.0   lubridate_1.8.0     assertthat_0.2.1   
    #> [52] rmarkdown_2.14      httr_1.4.3          rstudioapi_0.13    
    #> [55] R6_2.5.1            compiler_4.2.1

</details>

**Comment by juliasilge** [comment]
Can you tell me a bit more about what you have in the `params` for your model?

The template uses this:

```
params:
    board: !r pins::board_rsconnect()
    name: julia.silge/sacramento_rf
    version: NULL
```

This tries to connect to a [Connect](https://www.rstudio.com/products/connect/) pins board, and then gets a model called `julia.silge/sacramento_rf`. Did you replace this with your own model? If you are trying out the Model Card template with your own local model, you could store it [via `board_local()` or `board_folder()`](https://pins.rstudio.com/reference/board_folder.html).

**Comment by aropele** [comment]
Yes, the wrong `params` settings were the issue.

Thanks.
