### ISSUE TITLE
Support for mgcv::gam() models

### ISSUE THREAD

**Issue by kmasiello** [rstudio/vetiver-r#131]
Submitting on behalf of community member.  Would like to see support for GAMs models built from `mgcv`

**Comment by juliasilge** [comment]
@kmasiello do you know if this community member would be interested in taking a look at the PR before I merge it in?

**Comment by kmasiello** [comment]
That was super fast! Checking...  I'll get back to you as soon as possible. Thanks!

**Comment by kmasiello** [comment]
Hi Julia, the community member has not responded, so I think it's good to move forward without their comments.

**Comment by juliasilge** [comment]
Sounds good! 🙌 Thank you for the update.
