### ISSUE TITLE
Bug in glue_sys_reqs()

### ISSUE THREAD

**Issue by csgillespie** [rstudio/vetiver-r#142]
I think the following is incorrect, 

```
vetiver:::glue_sys_reqs("shiny")
#RUN apt-get update -qq && apt-get install -y --no-install-recommends \
 # make
```

as shiny should [depend on zlibg](https://packagemanager.rstudio.com/client/#/repos/1/packages/shiny) as well.

I think the error is this line: https://github.com/rstudio/vetiver-r/blob/8edec56b484dfb65e34e3cdf7e43ba272e7dc854/R/write-docker.R#L116

Happy to submit a PR.

**Comment by juliasilge** [comment]
Yeah, I think you're right that something has gone wrong there. The line before looks OK (this is for shiny):

```
> map(sys_reqs$requirements, pluck, "requirements", "packages")
[[1]]
[[1]][[1]]
[1] "make"


[[2]]
[[2]][[1]]
[1] "make"


[[3]]
[[3]][[1]]
[1] "make"

[[3]][[2]]
[1] "zlib1g-dev"
```

A PR would be fantastic, if you are able! Could you add a test for this function that is skipped on CRAN, for a few real packages?
