### ISSUE TITLE
Ability to use engine-specific serialization functions

### ISSUE THREAD

**Issue by smingerson** [rstudio/vetiver-r#15]
Exciting that the Tidymodels team is tackling this! 

Some engines, [such as xgboost](https://rdrr.io/cran/xgboost/man/xgb.save.html), have alternative methods of serialization that are recommended. I think using `pin_download()`/`pin_upload()` while providing the loading function to be recorded in the metadata would work okay. 

Edit: 
I was thinking about a workflow containing an xgboost model. My original suggestion seems insufficient at handling that. Maybe each engine (or workflow containing a model from that engine)  needs its own method of serialization, with rds as the default? I imagine the serialization methods would be defined in the package containing the model engine.

**Comment by juliasilge** [comment]
@smingerson If you are interested in trying out our new [bundle](https://github.com/rstudio/bundle) package for this kind of problem, now would be a good time! We will be moving bundle to CRAN soon, and then integrating the bundle methods into vetiver.
