### ISSUE TITLE
vetiver_write_docker with local pins should it add the folder to the docker container?

### ISSUE THREAD

**Issue by RMHogervorst** [rstudio/vetiver-r#155]
Hi Julia, 

I followed the [deploy tutorial ](https://vetiver.rstudio.com/get-started/deploy.html#generate-a-dockerfile).
I want to build a docker container with the model inside it (although I noticed that might [not be recommended?](https://github.com/rstudio/vetiver-r/issues/101#issuecomment-1149273592)) For now I envision a pipeline where you build a container for every new model version. 

So here is what I did:

* Create a model
```r
library(tidymodels)
library(vetiver)
library(pins)

car_mod <-
    workflow(mpg ~ ., decision_tree(mode = "regression")) %>%
    fit(mtcars)
```

* create a vetiver model from that model
* write the result to a board
* create the plumber file
* create a dockerfile
```r
v <- vetiver_model(car_mod, "cars_mpg")
model_board <- board_folder("pins-r", versioned = TRUE)
model_board %>% vetiver_pin_write(v)
vetiver_write_plumber(model_board, "cars_mpg",rsconnect = FALSE)
vetiver_write_docker(v)
```

But the dockerfile only copies the `vetiver_renv.lock` and `plumber.R` file. 

This is not a working container because it cannot find the board/pin.
```
Error in stopOnLine(lineNum, file[lineNum], e) :
  Error on line #7: 'b <- board_folder(path = "pins-r")' - Error in `abort_pin_missing()`:
! Can't find pin called 'cars_mpg'
```

- Am I overthinking this? is the pins part unnessary for vetiver?
- Is it bad practice to put the model inside the container?

Thanks for all the work!

**Comment by juliasilge** [comment]
The decision to keep the binary model object _outside_ the Docker container is purposeful on our part, like you saw in the earlier issue. In our opinion, the model needs to be versioned and located outside the container, for a more robust and flexible workflow. You are totally free to edit the Dockerfile and do this if it fits your particular use case better, but we [consider this an "off label" use](https://www.youtube.com/watch?v=izFssYRsLZs).

What you would do if your use case is better suited to having the model inside the Docker container is use `board_folder("your-folder-for-model-pin)` and then copy the folder where your pins are into the Docker container at build time. You can read more about [how `board_folder()` works](https://pins.rstudio.com/reference/board_folder.html) but this approach doesn't take advantage of pins versioning. 

It would look something like this:

```docker
# Generated by the vetiver package; edit with care

FROM rocker/r-ver:4.2.2
ENV RENV_CONFIG_REPOS_OVERRIDE https://packagemanager.rstudio.com/cran/latest

RUN apt-get update -qq && apt-get install -y --no-install-recommends \
  libcurl4-openssl-dev \
  libicu-dev \
  blah-blah-blah \
  && apt-get clean

COPY vetiver_renv.lock renv.lock
RUN Rscript -e "install.packages('renv')"
RUN Rscript -e "renv::restore()"
ADD your-folder-for-model-pin your-folder-for-model-pin
COPY plumber.R /opt/ml/plumber.R
EXPOSE 8000
ENTRYPOINT ["R", "-e", "pr <- plumber::plumb('/opt/ml/plumber.R'); pr$run(host = '0.0.0.0', port = 8000)"]
```

**Comment by RMHogervorst** [comment]
Thanks for your superfast answer and complete Dockerfile! Indeed the pin-versioning is lost when you copy the model to the model in the build step.

> In our opinion, the model needs to be versioned and located outside the container, for a more robust and flexible workflow. 

This is maybe not the right place, but could you someday expand on the rationale for versioning outside a container? I can see several pros and cons and love to learn about you and your team's rationale for this direction.

**Comment by juliasilge** [comment]
That is a great idea @RMHogervorst! We did a fair amount of user research that drove this decision (common failure modes, etc) and it would be good to summarize it, like in an upcoming talk.

**Comment by RMHogervorst** [comment]
Awesome, looking forward to it!
