### ISSUE TITLE
Is it possible to facilitate multiple models with a single endpoint?

### ISSUE THREAD

**Issue by JakeRuss** [rstudio/vetiver-r#156]
Hi Julia, 

The development on this package has been great to watch! 

For my project workflow at work, I deal with running 10-20 models at a time (all with different outcome variables) but the features in each model overlap quite a bit. I'm wondering if it is possible to serve predictions using one endpoint but allow the url structure to reference different models hosted on S3/Pins? Let me motivate the idea with a snippet from your Sacramento model in the README, 

````
endpoint <- vetiver_endpoint("http://127.0.0.1:8088/predict")
endpoint

new_sac <- Sacramento %>% 
    slice_sample(n = 20) %>% 
    select(type, sqft, beds, baths)

predict(endpoint, new_sac)
````

If I had a Sacramento model and a San Francisco model, could vetiver deploy them in such a way to allow me to retrieve predictions from both models on a single server? eg, Could I somehow send data and requests to...

````
http://127.0.0.1:8088/Sacramento/predict
http://127.0.0.1:8088/SanFran/predict
````
Do you have any advice or ideas for how you might handle this scenario?

**Comment by isabelizimm** [comment]
Hi Jake,

As a guideline:

- Input data is the same -> use one API
- Input data is not the same -> use multiple APIs

(These are not definitive rules. A lot of this is dependent upon architecture, how your deployment is set up, what works best for your organization, etc. And, vetiver allows you to break both of these rules!)

The vetiver API itself is made up of a combination of [vetiver_pr_post() and vetiver_pr_docs()](https://rstudio.github.io/vetiver-r/reference/vetiver_api.html#ref-usage) along with the path argument. You can compose these pieces manually to make different endpoints with the same input data prototype on the same API.

```
library(vetiver)
library(plumber)

cars_lm1 <- lm(mpg ~ ., data = mtcars)
v1 <- vetiver_model(cars_lm1, "cars_linear")

cars_lm2 <- lm(mpg ~ ., data = mtcars)
v2 <- vetiver_model(cars_lm2, "cars_linear")

pr() %>% 
  vetiver_pr_post(v1, path = "/v1") %>% 
  vetiver_pr_docs(v1) %>% 
  vetiver_pr_post(v2, path = "/v2") %>% 
  vetiver_pr_docs(v2) %>% 
  pr_run()
```

will allow you to make predictions at

```
http://127.0.0.1:8088/v1
http://127.0.0.1:8088/v2
```
the name of the endpoint itself can be anything you would like. I have a little [blog post](https://isabelizimm.github.io/posts/multiple-models-api/models.html) on this topic that might be useful as well!

**Comment by JakeRuss** [comment]
That is very cool! @isabelizimm Great blog post on the subject, too. I read those docs, but I did not consider that I could control the URL path text by changing the string supplied. This seems exactly what I was looking for.
