### ISSUE TITLE
vetiver_ptype gets congfused if lm has interaction terms

### ISSUE THREAD

**Issue by jtsuvile** [rstudio/vetiver-r#158]
I kept getting the following error when trying to make vetiver_model of a lm object, which I narrowed down to be an issue of ptype

> > vetiver_ptype(model)
> Error in `[.data.frame`(model$model, pred_names) : 
>   undefined columns selected

If I read the codebase correctly, it might be an issue of not taking out interaction terms of lm models before building the ptype resulting in the error. I'm not confident enough in the elegance of my solution to make a PR out of this, but have provided a solution that does seem to eliminate the error.

Minimal working example (with a possible way to fix the issue demonstrated)
```
library(vetiver)

data(mtcars)
model <- lm(mpg ~ cyl*gear+disp, data=mtcars)

# this does not work
vetiver_ptype(model)

# removing interaction terms from pred_names
vetiver_ptype_edited.lm <- function(model, ...) {
  pred_names <- attr(model$terms, "term.labels")
  # taking away interaction terms, they will always have a ':' in them
  pred_names_without_interaction <- pred_names[!grepl(':',pred_names)]
  ptype <- vctrs::vec_ptype(model$model[pred_names_without_interaction])
  tibble::as_tibble(ptype)
}

# this works
vetiver_ptype_edited.lm(model)
```

**Comment by juliasilge** [comment]
Thank you so much for this report @jtsuvile! 🙌 

I put together a fix for this in #160, if you would like to give it a try with your use case.
