### ISSUE TITLE
predict.vetiver_endpoint errors if all values in column are missing for xgboost model

### ISSUE THREAD

**Issue by btbroderick** [rstudio/vetiver-r#167]
I have a xgboost model that is trained with data that has missing values in a number of columns, so it should be able to handle new observations that have missing data.  The issue is if you try to predict on new data in whose has missing data for the whole column predict.vetiver_endpoint errors out.  It is very plausible I would want to make a prediction on 1 or 2 new observations that are missing for a feature. So I think this is a bug.  Here is my example adapted from the documentation.

`library(tidymodels)
library(vetiver)
library(pins)
library(plumber)
data("mtcars")
mtcars[1, ]$cyl <- NA_real_

# Fit Model
car_mod <-
  workflow(mpg ~ ., boost_tree(mode = "regression", engine = "xgboost")) %>%
  fit(mtcars)
# Create Vetiver Model
v <- vetiver_model(car_mod, "cars_mpg")

# Create and API for the model
pr() %>%
  vetiver_api(v) %>%
  pr_run(port = 8786)
`
Once this is running I call the endpoint from a different session

`
# WORKS even though some data is missing
m1 <- vetiver::vetiver_endpoint("http://127.0.0.1:8786/predict")
new_car <- tibble(cyl = c(NA_real_, 1),  disp = c(200,200),
                  hp = c(100,100), drat = c(3,3),
                  wt = c(3,3),   qsec = c(17, 17),
                  vs = c(0,0),   am = c(1,1),
                  gear = c(4,4), carb = c(2,2))
predict(m1, new_car)

# Doesn't work, all cyl data is missing
new_car <- tibble(cyl = c(NA_real_, NA_real_),  disp = c(200,200),
                  hp = c(100,100), drat = c(3,3),
                  wt = c(3,3),   qsec = c(17, 17),
                  vs = c(0,0),   am = c(1,1),
                  gear = c(4,4), carb = c(2,2))
predict(m1, new_car)`

ERROR:
`Error in `predict()`:
! Failed to predict: Error in `glubort()`:
! The following required columns are missing: 'cyl'.`

**Comment by juliasilge** [comment]
Thanks for the report @btbroderick!

Hmmm, this is going to take a bit digging, I think. The functions don't error when called directly in the same session:

``` r
library(tidymodels)
library(vetiver)
#> 
#> Attaching package: 'vetiver'
#> The following object is masked from 'package:tune':
#> 
#>     load_pkgs
car_mod <-
    workflow(mpg ~ cyl + disp, boost_tree(mode = "regression", engine = "xgboost")) %>%
    fit(mtcars)
v <- vetiver_model(car_mod, "cars_mpg")

new_car <- tibble(cyl = c(NA_real_, NA_real_), disp = c(200,200),
                  hp = c(100,100), drat = c(3,3),
                  wt = c(3,3), qsec = c(17, 17),
                  vs = c(0,0), am = c(1,1),
                  gear = c(4,4), carb = c(2,2))

vetiver_type_convert(new_car, v$ptype)
#> # A tibble: 2 × 10
#>     cyl  disp    hp  drat    wt  qsec    vs    am  gear  carb
#>   <dbl> <dbl> <dbl> <dbl> <dbl> <dbl> <dbl> <dbl> <dbl> <dbl>
#> 1    NA   200   100     3     3    17     0     1     4     2
#> 2    NA   200   100     3     3    17     0     1     4     2
## no error:
hardhat::validate_column_names(new_car, colnames(v$ptype))
```

<sup>Created on 2022-12-08 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

Something is going wrong in the new session.

**Comment by juliasilge** [comment]
Ah, it is when the conversion to JSON happens:

``` r
new_car <- tibble::tibble(cyl = c(NA_real_, NA_real_), disp = c(200,200),
                          hp = c(100,100), drat = c(3,3),
                          wt = c(3,3), qsec = c(17, 17),
                          vs = c(0,0), am = c(1,1),
                          gear = c(4,4), carb = c(2,2))
jsonlite::toJSON(new_car)
#> [{"disp":200,"hp":100,"drat":3,"wt":3,"qsec":17,"vs":0,"am":1,"gear":4,"carb":2},{"disp":200,"hp":100,"drat":3,"wt":3,"qsec":17,"vs":0,"am":1,"gear":4,"carb":2}]
```

<sup>Created on 2022-12-08 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

The missing column is dropped when the JSON is created.

**Comment by juliasilge** [comment]
We should try out using the `na` argument in jsonlite:

``` r
new_car <- tibble::tibble(cyl = c(NA_real_, NA_real_), 
                          disp = c(200,300),
                          hp = c(100,200))
jsonlite::toJSON(new_car, pretty = TRUE)
#> [
#>   {
#>     "disp": 200,
#>     "hp": 100
#>   },
#>   {
#>     "disp": 300,
#>     "hp": 200
#>   }
#> ]
jsonlite::toJSON(new_car, pretty = TRUE, na = "string")
#> [
#>   {
#>     "cyl": "NA",
#>     "disp": 200,
#>     "hp": 100
#>   },
#>   {
#>     "cyl": "NA",
#>     "disp": 300,
#>     "hp": 200
#>   }
#> ]
```

<sup>Created on 2022-12-08 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

**Comment by btbroderick** [comment]
Was also thinking that the dots(...) can be passed to toJSON and fromJSON in case use wants to change the behavior.  digits was one that came to mind with toJSON that might want to be controlled.
```r
predict.vetiver_endpoint <- function(object, new_data, ...) {
  browser()
  rlang::check_installed(c("jsonlite", "httr"))
  data_json <- jsonlite::toJSON(new_data, ....)
  ret <- httr::POST(object$url, ..., body = data_json)
  resp <- httr::content(ret, "text", encoding = "UTF-8")
  resp <- jsonlite::fromJSON(resp, ...)

  if (httr::status_code(ret) >= 300) {
    if (has_name(resp, "message")) {
      abort(glue("Failed to predict: {resp$message}"))
    } else {
      status <- httr::http_status(ret)
      abort(c("Failed to predict.", status$message))
    }
  }

  tibble::as_tibble(resp)
}
```

**Comment by btbroderick** [comment]
Also, thank you for your quick response on this! @juliasilge

**Comment by juliasilge** [comment]
We pass the dots through to `httr::POST()` right now which we need for authentication ([like this](https://docs.posit.co/connect/user/vetiver/#predict-from-your-model-endpoint)) so I don't think we can use the dots for something else.

I do think setting this argument will be OK for all use cases.
