### ISSUE TITLE
Using Vetiver for UMAPs

### ISSUE THREAD

**Issue by eleanor-m** [rstudio/vetiver-r#177]
Hi Posit team,

Thanks for your hard work on Vetiver - it looks like a very useful package that my team is looking at implementing for our supervised ML models.

I was wondering if it's possible to use Vetiver with UMAP models - that is, to version the models and also to use the API to project new data into existing models. As an example, we often need to project new data into previously-created UMAPs, and eventually update the UMAPs using all the available data. At present we simply track versions of UMAPs using a date stamp in the filename of the saved model object, but it would be great to have a more effective solution.

Vetiver doesn't appear to support UMAP directly (we are working in R with the uwot package), so initially we thought we could use the tidymodels framework.

However (as far as I can tell) Vetiver requires from tidymodels a "workflow" object on which the predict function can be called. The workflow object comprises a "recipe" part and a "model" part. The UMAP step is contained in the "recipe" as a pre-processing step, rather than as a "model". As a result, I haven't been able to create a workflow that can use a predict function to transform new data into UMAP coordinates.

Do you have any suggestions for how we can work around this issue? If it's not possible now, is this something that the Posit team is considering adding to Vetiver in the future?

Thank you!

**Comment by juliasilge** [comment]
Thanks so much for this suggestion @eleanor-m! I just added a possible way to support standalone recipes in #179 and we would love for you to try it out and see if you have feedback. You can install it with `devtools::install_github("rstudio/vetiver-r@add-recipes").

**Comment by eleanor-m** [comment]
Amazing, thanks @juliasilge, I will have a look and get back to you!
