### ISSUE TITLE
Help knowing how to debug issues with a vetiver model throwing NULL results in vetiver_api()?

### ISSUE THREAD

**Issue by pa-nathaniel** [rstudio/vetiver-r#180]
I have a trained vetiver model stored as an object `v` and I'm getting strange results when trying to call it within a Plumber API. While I unfortunately do not have a reprex, I do hope I can get some advice on how to debug!

Here's what I'm doing:

I have a trained vetiver model `v` that is of class `vetiver_model`

```
> v

── dime_lr_fit ─ <bundled_workflow> model for deployment 
A glmnet classification modeling workflow using 50 features
> class(v)
[1] "vetiver_model"
```

I can successfully  pass `v` through `vetiver_api()` and `plumber::pr_run()`

```
pr() %>%
  vetiver_api(v, type = "prob") %>%
  pr_run()
```

When open the GUI, the request body looks fine. However, when I try the request, I see an empty value is returned (see below)

![image](https://user-images.githubusercontent.com/90150945/221326234-798c891e-92a7-4839-9193-a2eb7524af6a.png)

We can successfully predict results locally using `predict(v)`, so we know the model itself does work.

My team has created similar vetiver models from historical data in the past and this has never happened and we're struggling to know how to debug it. Any advice or suggestions would be greatly appreciated, thank you!

**Comment by juliasilge** [comment]
Oh hmmmmm, mysterious! What happens if you set `debug = TRUE` when you set up the vetiver API, like this?

```r
pr() %>%
  vetiver_api(v, debug = TRUE, type = "prob") %>%
  pr_run()
```

I see that you are getting 200s so this might not help, but worth a try, I think. Also, what happens if you use just the default `type` (i.e. don't set `type = "prob"`)?

**Comment by pa-nathaniel** [comment]
Thank you so much for the fast guidance @juliasilge!

We tried your suggestions but couldn't quite resolve it :( 

However we did discover something that seemed to fix it: 

* The results above resulted from passing placeholder values for factor features that the model hadn't seen before (i.e.; "string" instead of an actual value)
* When we changed the values of the factor features to known values, we get valid outputs.
* This surprised us because we _think_ in past models, we were able to pass placeholder values and still get outputs.

I'm curious, what should the expected behavior be when a user passes 'new' factor values to a model? Is that something we should account for in the modelling process or is it something vetiver handles at all?

Thanks so much again for your help, I'll close with this comment as we're unblocked but would love your thoughts on the above if you have time, thanks!!!

**Comment by juliasilge** [comment]
Ah interesting. If you end up in this situation, I would expect you to see this error with `debug = TRUE`:
```
Error in `predict()`:
! Failed to predict: Error in `warn_to_error()`:
! [0, 1]: expected value in level set, but got 'string'
```

If `debug` is not `TRUE`, then you will just see "Failed to predict." I can't create an example where I see the behavior you observed (200 response but empty) so if you are able to create a reproducible example, that would be really helpful.

If you are using tidymodels and want the model to handle new, unseen levels in factors, you can [add `step_novel()`](https://recipes.tidymodels.org/reference/step_novel.html); take a look at the details about how to have a `workflow()` also be able to handle new levels. However, the vetiver checking of new data is pretty strict and will use the data from training to check factor levels even if you set that all up. If you want to turn off that type checking, you would [need to do `vetiver_model(save_prototype = FALSE)`](https://rstudio.github.io/vetiver-r/reference/vetiver_model.html).
