### ISSUE TITLE
board_s3() and paws.storage error

### ISSUE THREAD

**Issue by turalsadigov** [rstudio/vetiver-r#196]
I am running a little code that creates a linear model, and I use Vetiver to deploy it to AWS. When I create and run a Docker image, it throws the following error:

"Error in stopOnLine(lineNum, file[lineNum], e) : 
  Error on line rstudio/pins-r#6: 'library(vetiver)' - Error in `board_s3()` at plumber.R:7:0:
! The package "paws.storage" is required.
Calls: <Anonymous> ... tryCatchList -> tryCatchOne -> <Anonymous> -> stopOnLine
Execution halted"

I tried to manually add "paws. storage" to vetiver_renv.lock and include libxml2-dev in the Dockerfile, but still getting the same error. I also added paw.common, and paws.storage to plumber.R file. That did not help either. Can someone help me? Thanks!

**Comment by juliasilge** [comment]
You can read a little more about [why this happens in the pins docs](https://pins.rstudio.com/reference/board_s3.html#details) but in vetiver, we have some functions to help out with this. Specifically, [`vetiver_prepare_docker()`](https://rstudio.github.io/vetiver-r/reference/vetiver_prepare_docker.html) uses `additional_pkgs = required_pkgs(board)` to get the specific packages your board needs to work.

``` r
library(pins)

b <- board_s3(
  "pins-testing-julia", 
  profile = "PowerUser-158990117310", 
  region = "us-east-2"
)

## here how to find the needed packages manually:
required_pkgs(b)
#> [1] "paws.storage"

library(vetiver)
## Use this function to make your Dockerfile, renv.lock, and plumber file:
vetiver_prepare_docker(b, "cars-linear", path = tempdir())
#> The version of R recorded in the lockfile will be updated:
#> - R              [* -> 4.2.2]
#> 
#> * Lockfile written to 'vetiver_renv.lock'.
```

<sup>Created on 2023-04-16 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

These functions are in both the CRAN versions of pins and vetiver, so I don't think you need to do any special installation to use this.

You don't happen to be a SageMaker user, do you? We just added [better SageMaker support in vetiver](https://rstudio.github.io/vetiver-r/dev/reference/index.html#sagemaker), currently in the development version of vetiver.

**Comment by juliasilge** [comment]
Let us know if you have further questions! 🙌
