### ISSUE TITLE
Practice server.

### ISSUE THREAD

**Issue by nipnipj** [rstudio/vetiver-r#202]
Is there any rstudio/non-rstudio/AWS-sagemaker server that can be used to practice on the use vetiver for free?

**Comment by juliasilge** [comment]
There are definitely options available, depending on what you are wanting to practice!

For practicing/debugging making predictions, I will often run the API in one R session and then call it from another R session. I typically do this in RStudio using a [background job](https://docs.posit.co/ide/user/ide/guide/tools/jobs.html).

Another approach I use when I want to practice or debug deploying a whole model, I will use Docker locally. You can see [an example of that here](https://juliasilge.com/blog/lego-sets/).

Do either of these meet the needs you are thinking about? What specific things were you wanting to try out or practice?

**Comment by juliasilge** [comment]
Let us know if you have further questions. 🙌  My main advice would be to practice vetiver using Docker locally -- such an important tool for MLOps practitioners!
