### ISSUE TITLE
Handle folder pin boards in vetiver_write_docker()

### ISSUE THREAD

**Issue by JosiahParry** [rstudio/vetiver-r#211]
When the a folder pin board is used a la `board_folder()` in conjunction with `vetiver_write_docker()` the subsequent boad and pin is not made available to the Docker container that is defined by the Dockerfile. 

I see two possible ways of handling this:

1. Copy the folder structure and the pin into the docker container. For this to work one doesn't need all of the pins in the folder board but just the one that is the model object. This is the approach I took and it seemed to work quite well :) 
2. Mount a volume--which I don't really like. Model objects are typically (kinda) small so volumes seem overkill here.

**Comment by juliasilge** [comment]
Related to #101 and #155

I'll repeat some of what we've said on this before, to hopefully make this more searchable and clear. The decision to keep the binary model object _outside_ the Docker container is purposeful on our part, like you'll see in those other issues. In our opinion, the model needs to be versioned and located outside the container, for a more robust and flexible workflow. Isabel speaks a bit to this [in this talk starting around 19:00 or so](https://www.youtube.com/watch?v=HYvZ3HDJlf4) but in short, it doesn't set people up for success in the long term to store model artifact binaries in containers themselves, vs. in whatever versioned model registry situation is best for them (on Connect, S3, wherever).

That being said, you are totally free to edit the Dockerfile! We are not the boss of you! Feel free to do this if it fits your particular use case better, but we [consider this an "off label" use](https://www.youtube.com/watch?v=izFssYRsLZs).

I have a gist here that takes the approach of mounting a volume: https://gist.github.com/juliasilge/b4c04c80eed1481454e273be833ae3e1 

I wonder if we should add a short blurb about this to [this page](https://vetiver.rstudio.com/learn-more/deploy-with-docker.html).

**Comment by JosiahParry** [comment]
Thanks for the thorough response! Yeah, that all makes good sense and seems like the best approach :) 

I _was_ going to suggest a message or warning in `vetiver_write_docker()` to check for class `pins_board_folder` but the pin is irrelevant there! Given all that, I concur that adding it to the vetiver site would be best. I'll close the issue here and open one there.
