### ISSUE TITLE
Error when load package in renv

### ISSUE THREAD

**Issue by aephidayatuloh** [rstudio/vetiver-r#223]
Hi, 

I installed vetiver package in renv project and load it using `library(vetiver)`. I'm using R 4.3.1 but I encountered this error.

```
Error: package or namespace load failed for ‘vetiver’:
 .onLoad failed in loadNamespace() for 'vetiver', details:
  call: NULL
  error: internal error: dynamic() received unexpected call 'installed_packages(lib.loc = renv_libpaths_system(), priority = priority)'
```
Thanks for help.

**Comment by juliasilge** [comment]
Ah, I think this is related to rstudio/renv#1253 probably. The situation is that vetiver vendors a whole copy of renv internally, and there were upstream changes in renv that don't play nicely with how it is used in vetiver. This has been resolved, so I recommend that you use vetiver >= 0.2.1 (current CRAN version or install from GitHub) and/or the development version of renv. You may also want to try turning off that `renv.dynamic.enabled` option, like this:

```r
withr::local_options(list(renv.dynamic.enabled = FALSE))
```

Do you know what versions of vetiver and renv you had when you observed this problem?

**Comment by aephidayatuloh** [comment]
Hello @juliasilge, thanks for the response.

This is the vetiver and renv version
``` r
packageVersion("vetiver")
#> [1] '0.2.1'
packageVersion("renv")
#> [1] '0.17.3'
```

<sup>Created on 2023-06-23 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

And this `withr::local_options(list(renv.dynamic.enabled = FALSE))` solve the problem. 
Thanks for your help.
