### ISSUE TITLE
Python - Error in "vetiver.prepare_docker()" with the examples.

### ISSUE THREAD

**Issue by coforfe** [rstudio/vetiver-r#224]
Hi, 
Thanks again for your continuous effort to improve this library and for making equivalent to use it betwen R and Python.

It is fantastic to generate so easisy a FastAPI end-point and submit data for prediction!.

I am trying to reproduce the whole example in the documentation with Python, and I do not have any problem, except when I try to get the DockerFile with `vetiver.prepare_docker()`. 

I am using two approches to generate the DockerFile:

- one with the code in your `cars_mpg` example 
```python
vetiver.prepare_docker(model_board, "cars_mpg")
```

- and the other one by using what you have in the `superbowl_ml` example.

```python
vetiver.prepare_docker(
    model_board, 
    "cars_mpg",
    version = "20230619T163528Z-22feb",
    port = 8080
)
```
and both with errors...

Attached you can find some screenshots of the different errors I get.
From the errors, I do not know if I should provide an URL where the docker will be called....

Thanks,
Carlos.
P.S: I am using Vetiver's 0.2.1 version. 

![Captura de pantalla 2023-06-19 a las 16 41 02](https://github.com/rstudio/vetiver-r/assets/8349230/0f034fcd-ac91-42c1-b59c-5
![Captura de pantalla 2023-06-19 a las 16 41 19](https://github.com/rstudio/vetiver-r/assets/8349230/62628eec-9e46-465f-84d0-7cd06e6fcdb6)
1740855e027)
![Captura de pantalla 2023-06-19 a las 16 41 10](https://github.com/rstudio/vetiver-r/assets/8349230/806c6061-b6a0-49e1-9ec5-7ee544a2147e)

**Comment by isabelizimm** [comment]
Hi there! Are you able to to tell me what version of Python `pins` you are using?

**Comment by coforfe** [comment]
Hi Isabel,
Yes, of course...

It is 0.7.0... 
I did update `vetiver` but not `pins`... Let me update it and try again.

Thanks for your always quick answers!.
Carlos.

**Comment by coforfe** [comment]
Hi Isabel,

Yes!.
It worked after updating `pins` !.
It generated the:

- Dockerfile
- vetiver_requirements.txt
- app.py

I will try to run the Dockerfile and generate a prediction with all of this. 

Thanks again!
Carlos.
<img width="1082" alt="Captura de pantalla 2023-06-19 a las 21 00 29" src="https://github.com/rstudio/vetiver-r/assets/8349230/0c847f8f-466a-47d8-a978-d3f4ab3e5d26">

**Comment by isabelizimm** [comment]
Great to hear it!
