### ISSUE TITLE
Test vetiver with latest version of paws.common 0.6.0

### ISSUE THREAD

**Issue by DyfanJones** [rstudio/vetiver-r#238]
Hi all,

I am in the process in releasing the latest version of `paws.common 0.6.0` https://github.com/paws-r/paws/issues/657. `paws.common 0.6.0` comes with a new xml parser that has increased performance: https://github.com/paws-r/paws/pull/621. However I am going around all paws dependent packages to ensure the new xml parser doesn't break any existing code.

Is it possible to run your existing tests with the latest version of `paws.common 0.6.0`? If not please let me know how to set up my environment so that I can test these changes on your behalf.

To install paws.common 0.6.0 you can use r-universe:

```r
install.packages('paws.common', repos = 'https://paws-r.r-universe.dev')
```

Side note: From memory I believe all the current unit tests are mocked. I am happy to investigate an integrated test to ensure it doesn't break anything.

**Comment by juliasilge** [comment]
Yes, pretty much [everything is mocked](https://github.com/rstudio/vetiver-r/blob/main/tests/testthat/test-sagemaker.R) in vetiver so we won't see a failure in our tests. For whether it _really_ still works, then as long as [smdocker and paws.machine.learning both are good to go](https://github.com/rstudio/vetiver-r/blob/d085934f0014f15387fd782aabbe00cb74e6b176/R/sagemaker.R#L253) with the new paws.common, then vetiver should be fine.

Do smdocker and paws.machine.learning have any testing strategies that could give us some confidence about the change?

**Comment by DyfanJones** [comment]
All testing for paws is handled on paws.common. The XML parse tests goes through several scenarios which give me a lot of confidence that everything should be fine. However there isn't as much integrated testing.

For extra level of confidence I will spin up an integrated test. And upload the results in this ticket :)

**Comment by DyfanJones** [comment]
Using example: https://juliasilge.com/blog/vetiver-sagemaker/ I have created a successful integrated test.

I had to do a little fiddling with the structure so that I add a "dev" package to the docker.  For some reason I couldn't get r-universe to work (probably my vpc config, and I was too lazy to fix it :P). Any way here is my code.

```sh
# clone repo to sagemaker notebook
git clone https://github.com/paws-r/paws.git paws
```

```r
# used remotes to install paws.common from local file.
install.packages("remotes")
remotes::install_local("paws/paws.common",dependencies = F)

# install paws quickly when on sagemaker
install.packages('paws', repos = c(pawsr = 'https://paws-r-builds.s3.amazonaws.com/packages/latest/', CRAN = 'https://cloud.r-project.org'))
install.packages(c("smdocker", "vetiver", "tidymodels", "ranger", "plumber"))
```

```r
# create project folder to allow for docker editing :P
fs::dir_create("project")
fs::dir_copy("paws/paws.common", "project/paws.common")
```

```r
library(tidymodels)
data(ames)

set.seed(123)

ames_split <- ames %>%
  mutate(Sale_Price = log10(Sale_Price)) %>%
  mutate_if(is.integer, as.numeric) %>%
  initial_split(prop = 0.80, strata = Sale_Price)

ames_train <- training(ames_split)
ames_test  <- testing(ames_split)

rf_spec <- rand_forest(trees = 1000) %>% 
  set_engine("ranger") %>% 
  set_mode("regression")

rf_wflow <- 
  workflow(
    Sale_Price ~ Neighborhood + Gr_Liv_Area + Year_Built + Bldg_Type + 
      Latitude + Longitude,
    rf_spec
  )

rf_fit <- rf_wflow %>% fit(data = ames_train)

library(vetiver)
v <- vetiver_model(rf_fit, "ames-pricing")

library(pins)
## existing bucket:
identifier <- "my-s3-bucket"

board <- board_s3(bucket = identifier)
vetiver_pin_write(board, v)
```

Had to break `vetiver_sm_build` into it's parts so I could customise the dockerfile. This a minor change of adding a `COPY` command to include `paws.common` directory during build`. Also I had to update `vetiver_renv.lock` so that is didn't reference paws.common using the explicit path (as docker path would be different that sagemaker). This doesn't affect the overall test but I thought I would highlight it just incase you wanted to do any other testing.
```r
instance_type <- "ml.t2.medium"
name <- "ames-pricing"
repo_name <- glue::glue("vetiver-sagemaker-{name}:{strftime(Sys.time(), '%Y-%m-%d')}")
bucket <- board$bucket
path <- "project"

vetiver_prepare_docker(
    board = board,
    name = name,
    path = path,
    predict_args = list(path = "/invocations"),
    docker_args = list(port = 8080)
)
```

`smdocker` is happy to zip up all sub-directory for code build.
```r
image_uri <- smdocker::sm_build(
    repository = repo_name, 
    dir = path, 
    bucket = bucket
)
```
![image](https://github.com/rstudio/vetiver-r/assets/23235152/d71e6721-5061-409a-af3b-c497643c940d)

```r
tags <- list(
  `vetiver:pin_board` = glue::glue("s3://{identifier}/"), 
  `vetiver:r-ver` = getRversion()
)

model_name <- vetiver_sm_model(image_uri, tags = tags)

endpoint_args <- list(
  model_name = model_name, 
  instance_type = instance_type,
  tags = tags
)

endpoint <- do.call(vetiver_sm_endpoint, endpoint_args)
```
![image](https://github.com/rstudio/vetiver-r/assets/23235152/9a4afe1d-5da9-4081-8dcf-56a38195128a)

```r
new_homes <- ames_test %>% slice_sample(n = 50)
predict(endpoint, new_homes)
```
![image](https://github.com/rstudio/vetiver-r/assets/23235152/0cf56d50-1013-4023-bd5c-6723547b92d9)

```r
vetiver_sm_delete(endpoint)
```

Let me know if you want the dockerfile and `vetiver_renv.lock` files. Will upload them to github if needed 😄

**Comment by DyfanJones** [comment]
From this I am happy it is working as intended. Let me know if you are ok with me  ✅ vetiver @juliasilge.

**Comment by juliasilge** [comment]
Yeah, renv is not intended to handle local installations of R packages (like `devtools::install()` or similar) and I run into problems when I am trying to test renv functionality in vetiver itself. I often mock a function or something like that. I would have thought renv did OK with R-universe? But anyway, definitely can be tricky for testing.

Thank you so much for testing this out! Very happy to see the new changes, and let's call vetiver good to go. ✅

**Comment by DyfanJones** [comment]
Thanks for that. I will progress with the release of `paws.common 0.6.0` and then the release of `paws 0.4.0`
