### ISSUE TITLE
S3 method for pin_write

### ISSUE THREAD

**Issue by csgillespie** [rstudio/vetiver-r#245]
It would be nice if instead of

```
v <- vetiver_model(inspection_fit, "user.name/chicago-inspections-rstats")
board <- board_connect()
board |> vetiver_pin_write(v)
```
we had

```
board |> pin_write(v)
````

**Comment by juliasilge** [comment]
I totally get where you are coming from on this and we've talked about various ways of making `pin_write()` and friends a generic. However this has mostly been about dispatching off the _board_ (not the kind of object you want to save), as discussed here:

- https://github.com/rstudio/pins-r/issues/456

Given the way the [S3 methods in the pins package are set up](https://github.com/rstudio/pins-r/blob/main/NAMESPACE), I don't think this is likely to be doable with the package's current design. You can read about our current advice for folks to [read/write specific kinds of objects here](https://pins.rstudio.com/articles/customize-pins-metadata.html).

**Comment by csgillespie** [comment]
It always seems easy to the folk on the outside :)

It came to mind because during the workshop I just heard "write to a pins board" - so I did use {pins} (the workshop was clear, it was me).

**Comment by juliasilge** [comment]
Thanks again so much for the discussion! 🙌
