### ISSUE TITLE
vetiver::vetiver_sm_build taking a very long time?

### ISSUE THREAD

**Issue by sebsilas** [rstudio/vetiver-r#246]
Hi vetiver dev team. Thank you for this great package!

I know you said in your video that running `vetiver_sm_build` could take a while, but it's been running for nearly 7 hours for me so far, and the only log is:

> Created ECR Repository sagemaker-studio

Does that sound plausible?

Thanks,
Seb

**Comment by juliasilge** [comment]
Oh no, that doesn't sound right to me at all. For me, this would take maybe 30 min at most and certainly you should see logging while it is going. To maybe get a little more info, can you [walk through what `vetiver_sm_build()` does](https://github.com/rstudio/vetiver-r/blob/main/R/sagemaker.R) a bit more manually? First this (which I assume is fine):

```r
vetiver_prepare_docker(
        board = board,
        name = name,
        version = version,
        path = path,
        predict_args = predict_args,
        docker_args = docker_args
    )
```

And then do this:

```r
image_uri <- smdocker::sm_build(
        repository = repository,
        compute_type = compute_type,
        role = role,
        dir = path,
        bucket = bucket,
        vpc_id = vpc_id,
        subnet_ids = subnet_ids,
        security_group_ids = security_group_ids,
        log = log,
        ...
    )
```

Depending on what happens, we may need to loop in the Dyfan, the smdocker maintainer, who has been super helpful.

**Comment by sebsilas** [comment]
Thanks for the swift response!

It's `smdocker::sm_build` that is hanging. I can't work out why yet.

**Comment by juliasilge** [comment]
Can you maybe put together a teeny tiny example project (simpler than a vetiver Docker container) and use `smdocker::sm_build()` directly? And open up an issue [over at that repo](https://github.com/DyfanJones/sm-docker/issues) with the problems you are experiencing? 

Please do link it to this issue so I can know what is the problem, for the future. Good luck! 🙌

**Comment by sebsilas** [comment]
Ok, thank you. Quick question: does the workflow in your [video](https://www.youtube.com/watch?v=aeCcd-W1XXs) depend on running RStudio in AWS cloud?

**Comment by juliasilge** [comment]
In my video, I was in fact working from Posit Workbench on SageMaker, not locally. This is typically easier because our functions here in vetiver and the ones in smdocker have defaults that "just work" when you are working from SageMaker. However, you should be able to also do this when working locally as long as you have the roles and authentication set up correctly. Check out these resources for more on working locally:

- The details on "Execution role requirements" in these docs: https://dyfanjones.r-universe.dev/smdocker
- Dyfan's answer to another person with questions about working locally in this discussion: https://github.com/rstudio/vetiver-r/issues/215#issuecomment-1677086583

**Comment by sebsilas** [comment]
> In my video, I was in fact working from Posit Workbench on SageMaker, not locally. This is typically easier because our functions here in vetiver and the ones in smdocker have defaults that "just work" when you are working from SageMaker. However, you should be able to also do this when working locally as long as you have the roles and authentication set up correctly. Check out these resources for more on working locally:
> 
> * The details on "Execution role requirements" in these docs: https://dyfanjones.r-universe.dev/smdocker
> * Dyfan's answer to another person with questions about working locally in this discussion: [`vetiver_deploy_sagemaker()` fails the example #215 (comment)](https://github.com/rstudio/vetiver-r/issues/215#issuecomment-1677086583)

Great news. I can confirm I went through these steps, and now everything works! I think that specifically this was the issue:

> However, you might need to add your AWS S3 bucket ARN (amazon resource number) to it. The default role only allows s3 buckets that have "sagemaker" in the bucket title. So if you bucket is called "my-bucket" it will fail. You can add your bucket to the resources and it should work for you :)
> 
> {
>         ... # rest of the IAM role policy
>         {
>             "Effect": "Allow",
>             "Action": [
>                 "s3:GetObject",
>                 "s3:PutObject",
>                 "s3:DeleteObject",
>                 "s3:AbortMultipartUpload"
>             ],
>             "Resource": [
>                 "arn:aws:s3:::*SageMaker*",
>                 "arn:aws:s3:::*Sagemaker*",
>                 "arn:aws:s3:::*sagemaker*",
>                 "arn:aws:s3:::*my-bucket*", # add custom s3 bucket
>                 "arn:aws:s3:::*aws-glue*"
>             ]
>         }
>         ... # rest of the IAM role policy
> }


Thank you!

**Comment by juliasilge** [comment]
So great to hear! Since you are the second person to run into this, I am thinking we should add this to the docs somewhere.

**Comment by juliasilge** [comment]
@sebsilas If you have any thoughts on the docs I added in #249, please feel free to let me know!

**Comment by sebsilas** [comment]
> #249

Seems pretty clear to me. Thank you!
