### ISSUE TITLE
Connection refused for plumber API

### ISSUE THREAD

**Issue by F041** [rstudio/vetiver-r#275]
I have

```
FROM rocker/r-ver:4.3.1
ENV RENV_CONFIG_REPOS_OVERRIDE https://packagemanager.rstudio.com/cran/latest

RUN apt-get update -qq && apt-get install -y --no-install-recommends \
  libcurl4-openssl-dev \
  libicu-dev \
  libsodium-dev \
  libssl-dev \
  make \
  zlib1g-dev \
  && apt-get clean

RUN mkdir -p /opt/ml/pins-r
ADD pins-r/ /opt/ml/pins-r

COPY vetiver_renv.lock renv.lock
RUN Rscript -e "install.packages('renv')"
RUN Rscript -e "renv::restore()"
COPY plumber.R /opt/ml/plumber.R
EXPOSE 8080
ENTRYPOINT ["R", "-e", "pr <- plumber::plumb('/opt/ml/plumber.R'); pr$run(host = '0.0.0.0', port = 8080)"]
```

No matter which URL I choose from 
```
Running plumber API at http://0.0.0.0:8080
Running rapidoc Docs at http://127.0.0.1:8080/__docs__/
```

Every time I get ERR_CONNECTION_REFUSED

If I modify the url so that I get inside the function

```
#* @plumber
function(pr) {
    pr %>% vetiver_api(v)
}
```

I get the same problem 

I also tried to chang the FROM, as suggested here: https://stackoverflow.com/questions/63037408/problem-accessing-or-and-running-r-plumber-api-in-docker

Still without success

**Comment by F041** [comment]
> That sounds super frustrating! How did you go about running the docker container? For example, what did you do for this:
> 
> ```
> docker run -p 8080:8080 my-docker-name
> ```
> 

`{"error":"404 - Resource Not Found"}
`

About the workshop I have the following problem:
![image](https://github.com/rstudio/vetiver-r/assets/19621180/de7be8e0-a105-4b9a-9281-893c24ff3706)
Even though I tried solving it updating Rstudio, installing it in a project, saying "no"

**Comment by F041** [comment]
UPDATE: 
the

`{"error":"404 - Resource Not Found"} `

happens with http://0.0.0.0:8000/

the docs work

![image](https://github.com/rstudio/vetiver-r/assets/19621180/bef47ad5-788f-44a8-8ddd-7fc12ebb0281)

I checked this because I tried running a basic plumber script, to try to isolate the problem, and I had the same problem, where http://127.0.0.1:7346 returned the same error but http://127.0.0.1:7346/__docs__/ worked

**Comment by F041** [comment]
so the question becomes, why with `docker run my-docker-name` it gives ERR_CONNECTION_REFUSED and with 
`docker run -p 8080:8080 my-docker-name` it works?

**Comment by juliasilge** [comment]
You need to publish the container's port to the host via `-p`. You might want to check out [the documentation for `docker run`](https://docs.docker.com/reference/cli/docker/container/run/) as well as [these resources for learning more about Docker](https://docs.docker.com/reference/cli/docker/container/run/).

Let us know if you have further questions!

**Comment by F041** [comment]
I think you pasted the same link for the same two hyperlinks
