### ISSUE TITLE
recipes now support ptype extraction

### ISSUE THREAD

**Issue by EmilHvitfeldt** [rstudio/vetiver-r#286]
This will help with validations when using a recipe by itself in vetiver

1.1.0 included `recipes_ptype()` and `recipes_ptype_validate()`

older recipes that doesn't have information will return `NULL`

**Comment by juliasilge** [comment]
_Originally posted by @juliasilge in https://github.com/tidymodels/recipes/pull/1329#pullrequestreview-2094692530_

> In vetiver, we currently require users to pass in their "input prototype data" explicitly, as shown [in this test](https://github.com/rstudio/vetiver-r/blob/main/tests/testthat/test-recipe.R). With the change in this PR, we'd be able to get the `ptype` out automatically from the recipe itself, which is great!
>
> We would [change `vetiver_ptype.recipe()` so it reads the value](https://github.com/rstudio/vetiver-r/blob/main/R/recipe.R) off the recipe instead of looking for it from the user in the dots.
